---
version: "3"
services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: my-syncthing
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - /mnt/d:/var/syncthing
    network_mode: host
    restart: unless-stopped
